In [1]:
import numpy as np

In [36]:
np.array([2,4,56,422,32,1]) # 1D array 

array([  2,   4,  56, 422,  32,   1])

In [38]:
a = np.array([2,4,56,422,32,1]) #Vector 
print(a)

[  2   4  56 422  32   1]


In [40]:
type(a)

numpy.ndarray

In [60]:
new = np.array([[10,20,30],[11,22,33]])  # 2d array (matrix)
new

array([[10, 20, 30],
       [11, 22, 33]])

In [62]:
np.array([[10,20,30],[11,22,33],[21,31,41]])

array([[10, 20, 30],
       [11, 22, 33],
       [21, 31, 41]])

In [78]:
np.array([[22.1,32.1,42.1],[23,33,43]], dtype(float)) # type casting

array([[22.1, 32.1, 42.1],
       [23. , 33. , 43. ]])

In [80]:
type(new)

numpy.ndarray

In [112]:
new = np.array([[10,20,30],[11,22,33]])  # 2d array (matrix)
new

array([[10, 20, 30],
       [11, 22, 33]])

In [119]:
new = np.array([new],dtype=complex)
new    #converting elements into float

array([[[[[10.+0.j, 20.+0.j, 30.+0.j],
          [11.+0.j, 22.+0.j, 33.+0.j]]]]])

# Arange

In [123]:
np.arange(10,27)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [127]:
np.arange(0,30,2) # gives alternate numbers

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [129]:
np.arange(0,30,1) # gives serial numbers

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [133]:
np.arange(0,30,0) # 0 is invalid

ZeroDivisionError: division by zero

# Reshape

In [160]:
np.arange(1,10).reshape(3,3) # the coloum and rows has to fit the values given in arange elemants

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [172]:
np.arange(0,30).reshape(3,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [176]:
np.arange(0,30).reshape(10,2)

ValueError: cannot reshape array of size 30 into shape (10,2)

In [ ]:
# Zeroes & Ones 

In [183]:
np.zeros((5,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [186]:
np.ones((5,4))


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [192]:
np.random.random((10,5))

array([[0.41256228, 0.42806441, 0.319914  , 0.74677221, 0.88520006],
       [0.17695545, 0.74267161, 0.31059099, 0.72487485, 0.78251385],
       [0.31196355, 0.19057373, 0.68568068, 0.62465741, 0.01805619],
       [0.86748189, 0.78060503, 0.9384569 , 0.17127291, 0.50502369],
       [0.27118571, 0.78483873, 0.08706258, 0.56654494, 0.36031205],
       [0.79653706, 0.67912798, 0.94928735, 0.14570545, 0.31138352],
       [0.71054753, 0.037574  , 0.28571086, 0.6496218 , 0.44603604],
       [0.43406992, 0.45235224, 0.88253032, 0.95608503, 0.77759724],
       [0.87691851, 0.7642195 , 0.52243264, 0.18720718, 0.71849018],
       [0.65977503, 0.45075743, 0.539018  , 0.6992952 , 0.6899984 ]])

In [ ]:
# Linespace

In [208]:
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [210]:
np.linspace(15,55,7)

array([15.        , 21.66666667, 28.33333333, 35.        , 41.66666667,
       48.33333333, 55.        ])

In [ ]:
# Identity

In [213]:
np.identity(5) # creats 5*5 matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [215]:
# Array Attributes

In [224]:
a = np.arange(2,10)
a

array([2, 3, 4, 5, 6, 7, 8, 9])

In [246]:
a2 = np.arange(12, dtype=float).reshape(3,4)
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [274]:
a3 = np.arange(25, dtype=float).reshape(5,5)
a3

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.],
       [15., 16., 17., 18., 19.],
       [20., 21., 22., 23., 24.]])

In [270]:
a4 = np.arange(16, dtype=int).reshape(2,2,4)
a4

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

# zeros & ones

In [506]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [510]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

#linspace

In [517]:
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [522]:
np.linspace(10,50,5)

array([10., 20., 30., 40., 50.])

In [524]:
np.identity(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

# Array attributes

In [531]:
a1 = np.arange(5)
a1

array([0, 1, 2, 3, 4])

In [541]:
a2 = np.arange(12, dtype =int).reshape(3,4)
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [543]:
a3 = np.arange(8).reshape(2,2,2) # 3D --> Tensor 
a3 

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [553]:
a5 = np.arange(100).reshape(2,5,10)
a5

array([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]],

       [[50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
        [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]]])

In [557]:
new.astype(bool)

array([[[[[ True,  True,  True],
          [ True,  True,  True]]]]])

#   Array operations

In [564]:
z1 = np.arange(12).reshape(3,4) 
z2 = np.arange(12,24).reshape(3,4) 

In [568]:
print(z1)
print(z2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [570]:
z1 + 5 #scaler operations

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [572]:
z2 - 4

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [574]:
z1 * 2 # multiplication

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [586]:
z2**4 #power

array([[ 20736,  28561,  38416,  50625],
       [ 65536,  83521, 104976, 130321],
       [160000, 194481, 234256, 279841]], dtype=int32)

In [592]:
z1//2 # floor division

array([[0, 0, 1, 1],
       [2, 2, 3, 3],
       [4, 4, 5, 5]], dtype=int32)

In [596]:
z2 % 3 # module

array([[0, 1, 2, 0],
       [1, 2, 0, 1],
       [2, 0, 1, 2]], dtype=int32)

In [609]:
z1>5 # relational operations

array([[False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True]])

In [611]:
z1<5

array([[ True,  True,  True,  True],
       [ True, False, False, False],
       [False, False, False, False]])

In [613]:
z2>50

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [615]:
z2<50

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

#vector

In [622]:
print(z1)
print(z2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [620]:
z1+z2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [634]:
z1*z2 # 2 variables caluclation

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

In [628]:
z1//z2

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [630]:
z1-z2

array([[-12, -12, -12, -12],
       [-12, -12, -12, -12],
       [-12, -12, -12, -12]])

In [632]:
z1%z2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

#Array function

In [683]:
p1 = np.random.random((3,3))
p1

array([[0.7649754 , 0.31829711, 0.39527114],
       [0.51943882, 0.48056282, 0.35009315],
       [0.71244384, 0.86928312, 0.8527036 ]])

In [685]:
p1 = np.round(p1*100)
p1

array([[76., 32., 40.],
       [52., 48., 35.],
       [71., 87., 85.]])

In [687]:
np.max(p1)

87.0

In [689]:
np.min(p1)

32.0

In [691]:
np.sum(p1)

526.0

In [693]:
np.prod(p1)

4462032347136000.0

In [711]:
p1 # in matrix 0=column , 1=row

array([[76., 32., 40.],
       [52., 48., 35.],
       [71., 87., 85.]])

In [713]:
np.max(p1, axis=1)

array([76., 52., 87.])

In [715]:
np.max(p1, axis=0)

array([76., 87., 85.])

In [717]:
np.mean(p1,axis=0)

array([66.33333333, 55.66666667, 53.33333333])

In [721]:
np.std(p1) # standred deviation

20.347596697350394

In [723]:
np.std(p1, axis=0) 

array([10.33870828, 23.09882152, 22.48456261])

In [727]:
np.var(p1) # variance

414.0246913580247

#Trignometry functions

In [736]:
np.sin(p1) # sin

array([[ 0.56610764,  0.55142668,  0.74511316],
       [ 0.98662759, -0.76825466, -0.42818267],
       [ 0.95105465, -0.82181784, -0.17607562]])

In [740]:
np.cos(p1) # cos

array([[ 0.82433133,  0.83422336, -0.66693806],
       [-0.16299078, -0.64014434, -0.90369221],
       [-0.30902273,  0.56975033, -0.98437664]])

In [742]:
np.tan(p1) # tan

array([[ 0.68674769,  0.66100604, -1.11721493],
       [-6.05327238,  1.20012724,  0.47381472],
       [-3.0776204 , -1.44241747,  0.17887017]])

#dot products

In [757]:
r1 = np.arange(12).reshape(3,4) 
r2 = np.arange(12,24).reshape(4,3) 
print(r1)
print(r2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]


In [761]:
0*12+1*15+2*18+3*21

114

In [759]:
np.dot(r1,r2) # rows multiplie by columns

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [764]:
#Round to the nearest integer 
arr = np.array([1.2, 2.7, 3.5, 4.9]) 
rounded_arr = np.round(arr) 
print(rounded_arr) 

[1. 3. 4. 5.]


In [766]:
#Floor operation 
arr = np.array([1.2, 2.7, 3.5, 4.9]) 
floored_arr = np.floor(arr) 
print(floored_arr) 

[1. 2. 3. 4.]


In [768]:
# ceil
arr = np.array([1.2, 2.7, 3.5, 4.9]) 
ceiled_arr = np.ceil(arr) 
print(ceiled_arr)

[2. 3. 4. 5.]


In [770]:
np.floor(6.8)

6.0

In [3]:
np.random.randint(11,200,(5,10))

array([[168,  61,  17, 139, 171,  11, 161, 151, 183,  38],
       [ 62, 121,  59,  66, 109, 198, 103, 184,  55,  88],
       [ 42, 176,  25, 199,  75,  91,  33,  50, 120, 142],
       [ 27, 136,  28, 106, 158, 128, 174, 134,  38,  78],
       [149, 137,  80, 166,  21,  31, 191,  28,  65,  39]])

In [5]:
np.arange(1,26) .reshape(5,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [9]:
np.arange(1,26) .reshape(25,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24],
       [25]])

In [11]:
type(np)

module

In [21]:
b = np.random.randint(10,1997,(15,9))
b

array([[ 682, 1066, 1634, 1021,  301,  534, 1835, 1880, 1988],
       [ 283,  548, 1448, 1143, 1377,   31,  687,  259,  810],
       [ 209, 1667, 1774,  219,  602,  135, 1279, 1310, 1038],
       [ 794, 1412,  664,  686, 1621,  562,  561,  831, 1182],
       [  88,  440,  232, 1084, 1394,  756, 1884, 1087,  149],
       [ 744, 1829, 1414,  121,   53, 1564, 1468,  162, 1557],
       [ 537,  136, 1976, 1362,  573,  430,  443,  375, 1621],
       [1649,  859, 1548,  642,  157, 1279, 1314, 1644,  487],
       [ 346,  408,  448,  554,  288, 1371, 1944, 1386,  531],
       [  10,  693, 1427,  824, 1048,  909,  977, 1559,  785],
       [ 236, 1180, 1144, 1275, 1193, 1811,  946,  885, 1322],
       [ 207,  737,  791, 1159, 1133, 1628, 1761, 1399, 1297],
       [1250,  213,  616,   91,  698,  812, 1271,  685,  110],
       [ 148,  357,  808, 1959, 1283,  867,  219, 1639, 1638],
       [1020, 1360, 1913,   72,  526,  225, 1248,  709, 1425]])

In [19]:
type(bz)

numpy.ndarray

# slicing and comma

In [25]:
b[1,3]

1143

In [29]:
b[1:4]

array([[ 283,  548, 1448, 1143, 1377,   31,  687,  259,  810],
       [ 209, 1667, 1774,  219,  602,  135, 1279, 1310, 1038],
       [ 794, 1412,  664,  686, 1621,  562,  561,  831, 1182]])

In [31]:
b[1:-5]

array([[ 283,  548, 1448, 1143, 1377,   31,  687,  259,  810],
       [ 209, 1667, 1774,  219,  602,  135, 1279, 1310, 1038],
       [ 794, 1412,  664,  686, 1621,  562,  561,  831, 1182],
       [  88,  440,  232, 1084, 1394,  756, 1884, 1087,  149],
       [ 744, 1829, 1414,  121,   53, 1564, 1468,  162, 1557],
       [ 537,  136, 1976, 1362,  573,  430,  443,  375, 1621],
       [1649,  859, 1548,  642,  157, 1279, 1314, 1644,  487],
       [ 346,  408,  448,  554,  288, 1371, 1944, 1386,  531],
       [  10,  693, 1427,  824, 1048,  909,  977, 1559,  785]])

In [33]:
from numpy import *

In [ ]:
mat = np.arange(10,10)